on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - run: ./gradlew build

  release:
    runs-on: ubuntu-22.04
    steps:
      - run: echo ./build/libs